v = int(input('Digite um numero para extrair a tabuada: '))
print('-' * 15)

print('{} x {:2} = {}'.format(v, 1, v))
print('{} x {:2} = {}'.format(v, 2, v))
print('{} x {:2} = {}'.format(v, 3, v))
print('{} x {:2} = {}'.format(v, 4, v))
print('{} x {:2} = {}'.format(v, 5, v))
print('{} x {:2} = {}'.format(v, 6, v))
print('{} x {:2} = {}'.format(v, 7, v))
print('{} x {:2} = {}'.format(v, 8, v))
print('{} x {:2} = {}'.format(v, 9, v))
print('{} x {:2} = {}'.format(v, 10, v))

print('-' * 15)